name: 'Android'
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.4'
          bundler-cache: true

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install Dependencies
        run: bundle install

      - name: Make Gradlew executable
        run: chmod +x ./gradlew
        working-directory: android

      - name: Build Android
        run: bundle exec fastlane android beta
        working-directory: android

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
            name: assets
            path: |
                ${{ github.workspace }}/android/app/build/outputs/apk/release/app-release.apk
